### PR TITLE
A gem hasn't been released

### PR DESCRIPTION
**Pull request by brendon**
Sorry to use a PR for this but issues are disabled on this repo.

Would you be able to release an actual gem for this project? At the moment it's uninstallable unless one references the GitHub repo in the Gemfile :)

### CODE REVIEW

**Comment by dmitry** [comment]
Would be nice to move this to the capistrano-plugins as well.

**Comment by brendon** [comment]
Here was my solution in the end. It's simple enough not to require a plugin:

```ruby
append :linked_files, "config/master.key"

namespace :deploy do
  namespace :check do
    before :linked_files, :set_master_key do
      on roles(:app), in: :sequence, wait: 10 do
        unless test("[ -f #{shared_path}/config/master.key ]")
          upload! 'config/master.key', "#{shared_path}/config/master.key"
        end
      end
    end
  end
end
```

**Comment by dmitry** [comment]
@brendon thank you for sharing your solution. Totally makes sense!

**Comment by brendon** [comment]
You're most welcome! It's probably something that could be added to the capistrano-rails gem. I'll ping them and see what they think.

**Comment by brendon** [comment]
https://github.com/capistrano/rails/issues/231

**Comment by dmitry** [comment]
@brendon awesome, it's been merged. Could be closed here.
@virgoproz please note for the others that it was merged into the latest capistrano: https://github.com/capistrano/rails/pull/232

**Comment by brendon** [comment]
Hi @dmitry, unfortunately it was only a bit of documentation that was merged. It would still be good to see this as a gem release :)

**Comment by brendon** [comment]
I'll close this for now since the manually documented way must suit most peoples needs.

**Pull request closed without merging**
